version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - USER_SERVICE_ADDRESS=user-service:50051
      - PROMO_SERVICE_ADDRESS=promo-service:50052
      - EVENT_SERVICE_ADDRESS=event-service:50053
      - JWT_SECRET=your-secret-key
    depends_on:
      - user-service
      - promo-service
      - event-service
    networks:
      - app-network

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    ports:
      - "50051:50051"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=promoservice
      - JWT_SECRET=your-secret-key
      - DATABASE_URL=postgres://postgres:postgres@db:5432/promoservice?sslmode=disable
    depends_on:
      - db
    networks:
      - app-network

  promo-service:
    build:
      context: .
      dockerfile: promo-service/Dockerfile
    ports:
      - "50052:50052"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=promoservice
      - JWT_SECRET=your-secret-key
      - DATABASE_URL=postgres://postgres:postgres@db:5432/promoservice?sslmode=disable
    depends_on:
      - db
    networks:
      - app-network

  event-service:
    build:
      context: .
      dockerfile: event-service/Dockerfile
    ports:
      - "50053:50053"
    environment:
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - kafka
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - app-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - app-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8081:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    depends_on:
      - kafka
    networks:
      - app-network

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=promoservice
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./user-service/internal/repository/migrations:/migrations/user
      - ./promo-service/internal/repository/migrations:/migrations/promo
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge 