// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: event/event.proto

package event

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrackPromoViewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	PromoId       string                 `protobuf:"bytes,2,opt,name=promo_id,json=promoId,proto3" json:"promo_id,omitempty"`
	ViewedAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=viewed_at,json=viewedAt,proto3" json:"viewed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackPromoViewRequest) Reset() {
	*x = TrackPromoViewRequest{}
	mi := &file_event_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackPromoViewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackPromoViewRequest) ProtoMessage() {}

func (x *TrackPromoViewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackPromoViewRequest.ProtoReflect.Descriptor instead.
func (*TrackPromoViewRequest) Descriptor() ([]byte, []int) {
	return file_event_event_proto_rawDescGZIP(), []int{0}
}

func (x *TrackPromoViewRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *TrackPromoViewRequest) GetPromoId() string {
	if x != nil {
		return x.PromoId
	}
	return ""
}

func (x *TrackPromoViewRequest) GetViewedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ViewedAt
	}
	return nil
}

type TrackPromoViewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackPromoViewResponse) Reset() {
	*x = TrackPromoViewResponse{}
	mi := &file_event_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackPromoViewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackPromoViewResponse) ProtoMessage() {}

func (x *TrackPromoViewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackPromoViewResponse.ProtoReflect.Descriptor instead.
func (*TrackPromoViewResponse) Descriptor() ([]byte, []int) {
	return file_event_event_proto_rawDescGZIP(), []int{1}
}

func (x *TrackPromoViewResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type TrackPromoClickRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	PromoId       string                 `protobuf:"bytes,2,opt,name=promo_id,json=promoId,proto3" json:"promo_id,omitempty"`
	ClickedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=clicked_at,json=clickedAt,proto3" json:"clicked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackPromoClickRequest) Reset() {
	*x = TrackPromoClickRequest{}
	mi := &file_event_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackPromoClickRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackPromoClickRequest) ProtoMessage() {}

func (x *TrackPromoClickRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackPromoClickRequest.ProtoReflect.Descriptor instead.
func (*TrackPromoClickRequest) Descriptor() ([]byte, []int) {
	return file_event_event_proto_rawDescGZIP(), []int{2}
}

func (x *TrackPromoClickRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *TrackPromoClickRequest) GetPromoId() string {
	if x != nil {
		return x.PromoId
	}
	return ""
}

func (x *TrackPromoClickRequest) GetClickedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ClickedAt
	}
	return nil
}

type TrackPromoClickResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackPromoClickResponse) Reset() {
	*x = TrackPromoClickResponse{}
	mi := &file_event_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackPromoClickResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackPromoClickResponse) ProtoMessage() {}

func (x *TrackPromoClickResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackPromoClickResponse.ProtoReflect.Descriptor instead.
func (*TrackPromoClickResponse) Descriptor() ([]byte, []int) {
	return file_event_event_proto_rawDescGZIP(), []int{3}
}

func (x *TrackPromoClickResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type TrackPromoCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	PromoId       string                 `protobuf:"bytes,2,opt,name=promo_id,json=promoId,proto3" json:"promo_id,omitempty"`
	CommentText   string                 `protobuf:"bytes,3,opt,name=comment_text,json=commentText,proto3" json:"comment_text,omitempty"`
	CommentedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=commented_at,json=commentedAt,proto3" json:"commented_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackPromoCommentRequest) Reset() {
	*x = TrackPromoCommentRequest{}
	mi := &file_event_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackPromoCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackPromoCommentRequest) ProtoMessage() {}

func (x *TrackPromoCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackPromoCommentRequest.ProtoReflect.Descriptor instead.
func (*TrackPromoCommentRequest) Descriptor() ([]byte, []int) {
	return file_event_event_proto_rawDescGZIP(), []int{4}
}

func (x *TrackPromoCommentRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *TrackPromoCommentRequest) GetPromoId() string {
	if x != nil {
		return x.PromoId
	}
	return ""
}

func (x *TrackPromoCommentRequest) GetCommentText() string {
	if x != nil {
		return x.CommentText
	}
	return ""
}

func (x *TrackPromoCommentRequest) GetCommentedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CommentedAt
	}
	return nil
}

type TrackPromoCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackPromoCommentResponse) Reset() {
	*x = TrackPromoCommentResponse{}
	mi := &file_event_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackPromoCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackPromoCommentResponse) ProtoMessage() {}

func (x *TrackPromoCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackPromoCommentResponse.ProtoReflect.Descriptor instead.
func (*TrackPromoCommentResponse) Descriptor() ([]byte, []int) {
	return file_event_event_proto_rawDescGZIP(), []int{5}
}

func (x *TrackPromoCommentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetPromoCommentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PromoId       string                 `protobuf:"bytes,1,opt,name=promo_id,json=promoId,proto3" json:"promo_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPromoCommentsRequest) Reset() {
	*x = GetPromoCommentsRequest{}
	mi := &file_event_event_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPromoCommentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPromoCommentsRequest) ProtoMessage() {}

func (x *GetPromoCommentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_event_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPromoCommentsRequest.ProtoReflect.Descriptor instead.
func (*GetPromoCommentsRequest) Descriptor() ([]byte, []int) {
	return file_event_event_proto_rawDescGZIP(), []int{6}
}

func (x *GetPromoCommentsRequest) GetPromoId() string {
	if x != nil {
		return x.PromoId
	}
	return ""
}

func (x *GetPromoCommentsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetPromoCommentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetPromoCommentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*PromoComment        `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPromoCommentsResponse) Reset() {
	*x = GetPromoCommentsResponse{}
	mi := &file_event_event_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPromoCommentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPromoCommentsResponse) ProtoMessage() {}

func (x *GetPromoCommentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_event_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPromoCommentsResponse.ProtoReflect.Descriptor instead.
func (*GetPromoCommentsResponse) Descriptor() ([]byte, []int) {
	return file_event_event_proto_rawDescGZIP(), []int{7}
}

func (x *GetPromoCommentsResponse) GetComments() []*PromoComment {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *GetPromoCommentsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type PromoComment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	PromoId       string                 `protobuf:"bytes,3,opt,name=promo_id,json=promoId,proto3" json:"promo_id,omitempty"`
	CommentText   string                 `protobuf:"bytes,4,opt,name=comment_text,json=commentText,proto3" json:"comment_text,omitempty"`
	CommentedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=commented_at,json=commentedAt,proto3" json:"commented_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromoComment) Reset() {
	*x = PromoComment{}
	mi := &file_event_event_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromoComment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromoComment) ProtoMessage() {}

func (x *PromoComment) ProtoReflect() protoreflect.Message {
	mi := &file_event_event_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromoComment.ProtoReflect.Descriptor instead.
func (*PromoComment) Descriptor() ([]byte, []int) {
	return file_event_event_proto_rawDescGZIP(), []int{8}
}

func (x *PromoComment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PromoComment) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *PromoComment) GetPromoId() string {
	if x != nil {
		return x.PromoId
	}
	return ""
}

func (x *PromoComment) GetCommentText() string {
	if x != nil {
		return x.CommentText
	}
	return ""
}

func (x *PromoComment) GetCommentedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CommentedAt
	}
	return nil
}

type TrackClientRegistrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	RegisteredAt  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackClientRegistrationRequest) Reset() {
	*x = TrackClientRegistrationRequest{}
	mi := &file_event_event_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackClientRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackClientRegistrationRequest) ProtoMessage() {}

func (x *TrackClientRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_event_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackClientRegistrationRequest.ProtoReflect.Descriptor instead.
func (*TrackClientRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_event_event_proto_rawDescGZIP(), []int{9}
}

func (x *TrackClientRegistrationRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *TrackClientRegistrationRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *TrackClientRegistrationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TrackClientRegistrationRequest) GetRegisteredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RegisteredAt
	}
	return nil
}

type TrackClientRegistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackClientRegistrationResponse) Reset() {
	*x = TrackClientRegistrationResponse{}
	mi := &file_event_event_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackClientRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackClientRegistrationResponse) ProtoMessage() {}

func (x *TrackClientRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_event_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackClientRegistrationResponse.ProtoReflect.Descriptor instead.
func (*TrackClientRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_event_event_proto_rawDescGZIP(), []int{10}
}

func (x *TrackClientRegistrationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type TrackPromoCreatedRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PromoId        string                 `protobuf:"bytes,1,opt,name=promo_id,json=promoId,proto3" json:"promo_id,omitempty"`
	CreatorId      string                 `protobuf:"bytes,2,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	Code           string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	DiscountAmount float64                `protobuf:"fixed64,4,opt,name=discount_amount,json=discountAmount,proto3" json:"discount_amount,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TrackPromoCreatedRequest) Reset() {
	*x = TrackPromoCreatedRequest{}
	mi := &file_event_event_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackPromoCreatedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackPromoCreatedRequest) ProtoMessage() {}

func (x *TrackPromoCreatedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_event_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackPromoCreatedRequest.ProtoReflect.Descriptor instead.
func (*TrackPromoCreatedRequest) Descriptor() ([]byte, []int) {
	return file_event_event_proto_rawDescGZIP(), []int{11}
}

func (x *TrackPromoCreatedRequest) GetPromoId() string {
	if x != nil {
		return x.PromoId
	}
	return ""
}

func (x *TrackPromoCreatedRequest) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *TrackPromoCreatedRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *TrackPromoCreatedRequest) GetDiscountAmount() float64 {
	if x != nil {
		return x.DiscountAmount
	}
	return 0
}

func (x *TrackPromoCreatedRequest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type TrackPromoCreatedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackPromoCreatedResponse) Reset() {
	*x = TrackPromoCreatedResponse{}
	mi := &file_event_event_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackPromoCreatedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackPromoCreatedResponse) ProtoMessage() {}

func (x *TrackPromoCreatedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_event_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackPromoCreatedResponse.ProtoReflect.Descriptor instead.
func (*TrackPromoCreatedResponse) Descriptor() ([]byte, []int) {
	return file_event_event_proto_rawDescGZIP(), []int{12}
}

func (x *TrackPromoCreatedResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type TrackPromoUpdatedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PromoId       string                 `protobuf:"bytes,1,opt,name=promo_id,json=promoId,proto3" json:"promo_id,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,2,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	UpdatedFields []string               `protobuf:"bytes,3,rep,name=updated_fields,json=updatedFields,proto3" json:"updated_fields,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackPromoUpdatedRequest) Reset() {
	*x = TrackPromoUpdatedRequest{}
	mi := &file_event_event_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackPromoUpdatedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackPromoUpdatedRequest) ProtoMessage() {}

func (x *TrackPromoUpdatedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_event_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackPromoUpdatedRequest.ProtoReflect.Descriptor instead.
func (*TrackPromoUpdatedRequest) Descriptor() ([]byte, []int) {
	return file_event_event_proto_rawDescGZIP(), []int{13}
}

func (x *TrackPromoUpdatedRequest) GetPromoId() string {
	if x != nil {
		return x.PromoId
	}
	return ""
}

func (x *TrackPromoUpdatedRequest) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *TrackPromoUpdatedRequest) GetUpdatedFields() []string {
	if x != nil {
		return x.UpdatedFields
	}
	return nil
}

func (x *TrackPromoUpdatedRequest) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type TrackPromoUpdatedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackPromoUpdatedResponse) Reset() {
	*x = TrackPromoUpdatedResponse{}
	mi := &file_event_event_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackPromoUpdatedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackPromoUpdatedResponse) ProtoMessage() {}

func (x *TrackPromoUpdatedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_event_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackPromoUpdatedResponse.ProtoReflect.Descriptor instead.
func (*TrackPromoUpdatedResponse) Descriptor() ([]byte, []int) {
	return file_event_event_proto_rawDescGZIP(), []int{14}
}

func (x *TrackPromoUpdatedResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type TrackPromoDeletedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PromoId       string                 `protobuf:"bytes,1,opt,name=promo_id,json=promoId,proto3" json:"promo_id,omitempty"`
	DeletedBy     string                 `protobuf:"bytes,2,opt,name=deleted_by,json=deletedBy,proto3" json:"deleted_by,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackPromoDeletedRequest) Reset() {
	*x = TrackPromoDeletedRequest{}
	mi := &file_event_event_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackPromoDeletedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackPromoDeletedRequest) ProtoMessage() {}

func (x *TrackPromoDeletedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_event_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackPromoDeletedRequest.ProtoReflect.Descriptor instead.
func (*TrackPromoDeletedRequest) Descriptor() ([]byte, []int) {
	return file_event_event_proto_rawDescGZIP(), []int{15}
}

func (x *TrackPromoDeletedRequest) GetPromoId() string {
	if x != nil {
		return x.PromoId
	}
	return ""
}

func (x *TrackPromoDeletedRequest) GetDeletedBy() string {
	if x != nil {
		return x.DeletedBy
	}
	return ""
}

func (x *TrackPromoDeletedRequest) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type TrackPromoDeletedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackPromoDeletedResponse) Reset() {
	*x = TrackPromoDeletedResponse{}
	mi := &file_event_event_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackPromoDeletedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackPromoDeletedResponse) ProtoMessage() {}

func (x *TrackPromoDeletedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_event_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackPromoDeletedResponse.ProtoReflect.Descriptor instead.
func (*TrackPromoDeletedResponse) Descriptor() ([]byte, []int) {
	return file_event_event_proto_rawDescGZIP(), []int{16}
}

func (x *TrackPromoDeletedResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type TrackUserProfileUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UpdatedFields []string               `protobuf:"bytes,2,rep,name=updated_fields,json=updatedFields,proto3" json:"updated_fields,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackUserProfileUpdateRequest) Reset() {
	*x = TrackUserProfileUpdateRequest{}
	mi := &file_event_event_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackUserProfileUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackUserProfileUpdateRequest) ProtoMessage() {}

func (x *TrackUserProfileUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_event_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackUserProfileUpdateRequest.ProtoReflect.Descriptor instead.
func (*TrackUserProfileUpdateRequest) Descriptor() ([]byte, []int) {
	return file_event_event_proto_rawDescGZIP(), []int{17}
}

func (x *TrackUserProfileUpdateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TrackUserProfileUpdateRequest) GetUpdatedFields() []string {
	if x != nil {
		return x.UpdatedFields
	}
	return nil
}

func (x *TrackUserProfileUpdateRequest) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type TrackUserProfileUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackUserProfileUpdateResponse) Reset() {
	*x = TrackUserProfileUpdateResponse{}
	mi := &file_event_event_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackUserProfileUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackUserProfileUpdateResponse) ProtoMessage() {}

func (x *TrackUserProfileUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_event_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackUserProfileUpdateResponse.ProtoReflect.Descriptor instead.
func (*TrackUserProfileUpdateResponse) Descriptor() ([]byte, []int) {
	return file_event_event_proto_rawDescGZIP(), []int{18}
}

func (x *TrackUserProfileUpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_event_event_proto protoreflect.FileDescriptor

const file_event_event_proto_rawDesc = "" +
	"\n" +
	"\x11event/event.proto\x12\x05event\x1a\x1fgoogle/protobuf/timestamp.proto\"\x88\x01\n" +
	"\x15TrackPromoViewRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x19\n" +
	"\bpromo_id\x18\x02 \x01(\tR\apromoId\x127\n" +
	"\tviewed_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bviewedAt\"2\n" +
	"\x16TrackPromoViewResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x8b\x01\n" +
	"\x16TrackPromoClickRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x19\n" +
	"\bpromo_id\x18\x02 \x01(\tR\apromoId\x129\n" +
	"\n" +
	"clicked_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tclickedAt\"3\n" +
	"\x17TrackPromoClickResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xb4\x01\n" +
	"\x18TrackPromoCommentRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x19\n" +
	"\bpromo_id\x18\x02 \x01(\tR\apromoId\x12!\n" +
	"\fcomment_text\x18\x03 \x01(\tR\vcommentText\x12=\n" +
	"\fcommented_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vcommentedAt\"5\n" +
	"\x19TrackPromoCommentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"e\n" +
	"\x17GetPromoCommentsRequest\x12\x19\n" +
	"\bpromo_id\x18\x01 \x01(\tR\apromoId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"l\n" +
	"\x18GetPromoCommentsResponse\x12/\n" +
	"\bcomments\x18\x01 \x03(\v2\x13.event.PromoCommentR\bcomments\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\xb8\x01\n" +
	"\fPromoComment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x19\n" +
	"\bpromo_id\x18\x03 \x01(\tR\apromoId\x12!\n" +
	"\fcomment_text\x18\x04 \x01(\tR\vcommentText\x12=\n" +
	"\fcommented_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vcommentedAt\"\xa8\x01\n" +
	"\x1eTrackClientRegistrationRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12?\n" +
	"\rregistered_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\fregisteredAt\";\n" +
	"\x1fTrackClientRegistrationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xcc\x01\n" +
	"\x18TrackPromoCreatedRequest\x12\x19\n" +
	"\bpromo_id\x18\x01 \x01(\tR\apromoId\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x02 \x01(\tR\tcreatorId\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12'\n" +
	"\x0fdiscount_amount\x18\x04 \x01(\x01R\x0ediscountAmount\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"5\n" +
	"\x19TrackPromoCreatedResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xb6\x01\n" +
	"\x18TrackPromoUpdatedRequest\x12\x19\n" +
	"\bpromo_id\x18\x01 \x01(\tR\apromoId\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x02 \x01(\tR\tupdatedBy\x12%\n" +
	"\x0eupdated_fields\x18\x03 \x03(\tR\rupdatedFields\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"5\n" +
	"\x19TrackPromoUpdatedResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x8f\x01\n" +
	"\x18TrackPromoDeletedRequest\x12\x19\n" +
	"\bpromo_id\x18\x01 \x01(\tR\apromoId\x12\x1d\n" +
	"\n" +
	"deleted_by\x18\x02 \x01(\tR\tdeletedBy\x129\n" +
	"\n" +
	"deleted_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"5\n" +
	"\x19TrackPromoDeletedResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x9a\x01\n" +
	"\x1dTrackUserProfileUpdateRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12%\n" +
	"\x0eupdated_fields\x18\x02 \x03(\tR\rupdatedFields\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\":\n" +
	"\x1eTrackUserProfileUpdateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xb5\x06\n" +
	"\fEventService\x12M\n" +
	"\x0eTrackPromoView\x12\x1c.event.TrackPromoViewRequest\x1a\x1d.event.TrackPromoViewResponse\x12P\n" +
	"\x0fTrackPromoClick\x12\x1d.event.TrackPromoClickRequest\x1a\x1e.event.TrackPromoClickResponse\x12V\n" +
	"\x11TrackPromoComment\x12\x1f.event.TrackPromoCommentRequest\x1a .event.TrackPromoCommentResponse\x12S\n" +
	"\x10GetPromoComments\x12\x1e.event.GetPromoCommentsRequest\x1a\x1f.event.GetPromoCommentsResponse\x12h\n" +
	"\x17TrackClientRegistration\x12%.event.TrackClientRegistrationRequest\x1a&.event.TrackClientRegistrationResponse\x12V\n" +
	"\x11TrackPromoCreated\x12\x1f.event.TrackPromoCreatedRequest\x1a .event.TrackPromoCreatedResponse\x12V\n" +
	"\x11TrackPromoUpdated\x12\x1f.event.TrackPromoUpdatedRequest\x1a .event.TrackPromoUpdatedResponse\x12V\n" +
	"\x11TrackPromoDeleted\x12\x1f.event.TrackPromoDeletedRequest\x1a .event.TrackPromoDeletedResponse\x12e\n" +
	"\x16TrackUserProfileUpdate\x12$.event.TrackUserProfileUpdateRequest\x1a%.event.TrackUserProfileUpdateResponseB,Z*github.com/sarvar/PromoService/proto/eventb\x06proto3"

var (
	file_event_event_proto_rawDescOnce sync.Once
	file_event_event_proto_rawDescData []byte
)

func file_event_event_proto_rawDescGZIP() []byte {
	file_event_event_proto_rawDescOnce.Do(func() {
		file_event_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_event_proto_rawDesc), len(file_event_event_proto_rawDesc)))
	})
	return file_event_event_proto_rawDescData
}

var file_event_event_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_event_event_proto_goTypes = []any{
	(*TrackPromoViewRequest)(nil),           // 0: event.TrackPromoViewRequest
	(*TrackPromoViewResponse)(nil),          // 1: event.TrackPromoViewResponse
	(*TrackPromoClickRequest)(nil),          // 2: event.TrackPromoClickRequest
	(*TrackPromoClickResponse)(nil),         // 3: event.TrackPromoClickResponse
	(*TrackPromoCommentRequest)(nil),        // 4: event.TrackPromoCommentRequest
	(*TrackPromoCommentResponse)(nil),       // 5: event.TrackPromoCommentResponse
	(*GetPromoCommentsRequest)(nil),         // 6: event.GetPromoCommentsRequest
	(*GetPromoCommentsResponse)(nil),        // 7: event.GetPromoCommentsResponse
	(*PromoComment)(nil),                    // 8: event.PromoComment
	(*TrackClientRegistrationRequest)(nil),  // 9: event.TrackClientRegistrationRequest
	(*TrackClientRegistrationResponse)(nil), // 10: event.TrackClientRegistrationResponse
	(*TrackPromoCreatedRequest)(nil),        // 11: event.TrackPromoCreatedRequest
	(*TrackPromoCreatedResponse)(nil),       // 12: event.TrackPromoCreatedResponse
	(*TrackPromoUpdatedRequest)(nil),        // 13: event.TrackPromoUpdatedRequest
	(*TrackPromoUpdatedResponse)(nil),       // 14: event.TrackPromoUpdatedResponse
	(*TrackPromoDeletedRequest)(nil),        // 15: event.TrackPromoDeletedRequest
	(*TrackPromoDeletedResponse)(nil),       // 16: event.TrackPromoDeletedResponse
	(*TrackUserProfileUpdateRequest)(nil),   // 17: event.TrackUserProfileUpdateRequest
	(*TrackUserProfileUpdateResponse)(nil),  // 18: event.TrackUserProfileUpdateResponse
	(*timestamppb.Timestamp)(nil),           // 19: google.protobuf.Timestamp
}
var file_event_event_proto_depIdxs = []int32{
	19, // 0: event.TrackPromoViewRequest.viewed_at:type_name -> google.protobuf.Timestamp
	19, // 1: event.TrackPromoClickRequest.clicked_at:type_name -> google.protobuf.Timestamp
	19, // 2: event.TrackPromoCommentRequest.commented_at:type_name -> google.protobuf.Timestamp
	8,  // 3: event.GetPromoCommentsResponse.comments:type_name -> event.PromoComment
	19, // 4: event.PromoComment.commented_at:type_name -> google.protobuf.Timestamp
	19, // 5: event.TrackClientRegistrationRequest.registered_at:type_name -> google.protobuf.Timestamp
	19, // 6: event.TrackPromoCreatedRequest.created_at:type_name -> google.protobuf.Timestamp
	19, // 7: event.TrackPromoUpdatedRequest.updated_at:type_name -> google.protobuf.Timestamp
	19, // 8: event.TrackPromoDeletedRequest.deleted_at:type_name -> google.protobuf.Timestamp
	19, // 9: event.TrackUserProfileUpdateRequest.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 10: event.EventService.TrackPromoView:input_type -> event.TrackPromoViewRequest
	2,  // 11: event.EventService.TrackPromoClick:input_type -> event.TrackPromoClickRequest
	4,  // 12: event.EventService.TrackPromoComment:input_type -> event.TrackPromoCommentRequest
	6,  // 13: event.EventService.GetPromoComments:input_type -> event.GetPromoCommentsRequest
	9,  // 14: event.EventService.TrackClientRegistration:input_type -> event.TrackClientRegistrationRequest
	11, // 15: event.EventService.TrackPromoCreated:input_type -> event.TrackPromoCreatedRequest
	13, // 16: event.EventService.TrackPromoUpdated:input_type -> event.TrackPromoUpdatedRequest
	15, // 17: event.EventService.TrackPromoDeleted:input_type -> event.TrackPromoDeletedRequest
	17, // 18: event.EventService.TrackUserProfileUpdate:input_type -> event.TrackUserProfileUpdateRequest
	1,  // 19: event.EventService.TrackPromoView:output_type -> event.TrackPromoViewResponse
	3,  // 20: event.EventService.TrackPromoClick:output_type -> event.TrackPromoClickResponse
	5,  // 21: event.EventService.TrackPromoComment:output_type -> event.TrackPromoCommentResponse
	7,  // 22: event.EventService.GetPromoComments:output_type -> event.GetPromoCommentsResponse
	10, // 23: event.EventService.TrackClientRegistration:output_type -> event.TrackClientRegistrationResponse
	12, // 24: event.EventService.TrackPromoCreated:output_type -> event.TrackPromoCreatedResponse
	14, // 25: event.EventService.TrackPromoUpdated:output_type -> event.TrackPromoUpdatedResponse
	16, // 26: event.EventService.TrackPromoDeleted:output_type -> event.TrackPromoDeletedResponse
	18, // 27: event.EventService.TrackUserProfileUpdate:output_type -> event.TrackUserProfileUpdateResponse
	19, // [19:28] is the sub-list for method output_type
	10, // [10:19] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_event_event_proto_init() }
func file_event_event_proto_init() {
	if File_event_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_event_proto_rawDesc), len(file_event_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_event_event_proto_goTypes,
		DependencyIndexes: file_event_event_proto_depIdxs,
		MessageInfos:      file_event_event_proto_msgTypes,
	}.Build()
	File_event_event_proto = out.File
	file_event_event_proto_goTypes = nil
	file_event_event_proto_depIdxs = nil
}
