// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: event/event.proto

package event

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventService_TrackPromoView_FullMethodName          = "/event.EventService/TrackPromoView"
	EventService_TrackPromoClick_FullMethodName         = "/event.EventService/TrackPromoClick"
	EventService_TrackPromoComment_FullMethodName       = "/event.EventService/TrackPromoComment"
	EventService_GetPromoComments_FullMethodName        = "/event.EventService/GetPromoComments"
	EventService_TrackClientRegistration_FullMethodName = "/event.EventService/TrackClientRegistration"
	EventService_TrackPromoCreated_FullMethodName       = "/event.EventService/TrackPromoCreated"
	EventService_TrackPromoUpdated_FullMethodName       = "/event.EventService/TrackPromoUpdated"
	EventService_TrackPromoDeleted_FullMethodName       = "/event.EventService/TrackPromoDeleted"
	EventService_TrackUserProfileUpdate_FullMethodName  = "/event.EventService/TrackUserProfileUpdate"
)

// EventServiceClient is the client API for EventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventServiceClient interface {
	TrackPromoView(ctx context.Context, in *TrackPromoViewRequest, opts ...grpc.CallOption) (*TrackPromoViewResponse, error)
	TrackPromoClick(ctx context.Context, in *TrackPromoClickRequest, opts ...grpc.CallOption) (*TrackPromoClickResponse, error)
	TrackPromoComment(ctx context.Context, in *TrackPromoCommentRequest, opts ...grpc.CallOption) (*TrackPromoCommentResponse, error)
	GetPromoComments(ctx context.Context, in *GetPromoCommentsRequest, opts ...grpc.CallOption) (*GetPromoCommentsResponse, error)
	TrackClientRegistration(ctx context.Context, in *TrackClientRegistrationRequest, opts ...grpc.CallOption) (*TrackClientRegistrationResponse, error)
	TrackPromoCreated(ctx context.Context, in *TrackPromoCreatedRequest, opts ...grpc.CallOption) (*TrackPromoCreatedResponse, error)
	TrackPromoUpdated(ctx context.Context, in *TrackPromoUpdatedRequest, opts ...grpc.CallOption) (*TrackPromoUpdatedResponse, error)
	TrackPromoDeleted(ctx context.Context, in *TrackPromoDeletedRequest, opts ...grpc.CallOption) (*TrackPromoDeletedResponse, error)
	TrackUserProfileUpdate(ctx context.Context, in *TrackUserProfileUpdateRequest, opts ...grpc.CallOption) (*TrackUserProfileUpdateResponse, error)
}

type eventServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEventServiceClient(cc grpc.ClientConnInterface) EventServiceClient {
	return &eventServiceClient{cc}
}

func (c *eventServiceClient) TrackPromoView(ctx context.Context, in *TrackPromoViewRequest, opts ...grpc.CallOption) (*TrackPromoViewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrackPromoViewResponse)
	err := c.cc.Invoke(ctx, EventService_TrackPromoView_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) TrackPromoClick(ctx context.Context, in *TrackPromoClickRequest, opts ...grpc.CallOption) (*TrackPromoClickResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrackPromoClickResponse)
	err := c.cc.Invoke(ctx, EventService_TrackPromoClick_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) TrackPromoComment(ctx context.Context, in *TrackPromoCommentRequest, opts ...grpc.CallOption) (*TrackPromoCommentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrackPromoCommentResponse)
	err := c.cc.Invoke(ctx, EventService_TrackPromoComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetPromoComments(ctx context.Context, in *GetPromoCommentsRequest, opts ...grpc.CallOption) (*GetPromoCommentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPromoCommentsResponse)
	err := c.cc.Invoke(ctx, EventService_GetPromoComments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) TrackClientRegistration(ctx context.Context, in *TrackClientRegistrationRequest, opts ...grpc.CallOption) (*TrackClientRegistrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrackClientRegistrationResponse)
	err := c.cc.Invoke(ctx, EventService_TrackClientRegistration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) TrackPromoCreated(ctx context.Context, in *TrackPromoCreatedRequest, opts ...grpc.CallOption) (*TrackPromoCreatedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrackPromoCreatedResponse)
	err := c.cc.Invoke(ctx, EventService_TrackPromoCreated_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) TrackPromoUpdated(ctx context.Context, in *TrackPromoUpdatedRequest, opts ...grpc.CallOption) (*TrackPromoUpdatedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrackPromoUpdatedResponse)
	err := c.cc.Invoke(ctx, EventService_TrackPromoUpdated_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) TrackPromoDeleted(ctx context.Context, in *TrackPromoDeletedRequest, opts ...grpc.CallOption) (*TrackPromoDeletedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrackPromoDeletedResponse)
	err := c.cc.Invoke(ctx, EventService_TrackPromoDeleted_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) TrackUserProfileUpdate(ctx context.Context, in *TrackUserProfileUpdateRequest, opts ...grpc.CallOption) (*TrackUserProfileUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrackUserProfileUpdateResponse)
	err := c.cc.Invoke(ctx, EventService_TrackUserProfileUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventServiceServer is the server API for EventService service.
// All implementations must embed UnimplementedEventServiceServer
// for forward compatibility.
type EventServiceServer interface {
	TrackPromoView(context.Context, *TrackPromoViewRequest) (*TrackPromoViewResponse, error)
	TrackPromoClick(context.Context, *TrackPromoClickRequest) (*TrackPromoClickResponse, error)
	TrackPromoComment(context.Context, *TrackPromoCommentRequest) (*TrackPromoCommentResponse, error)
	GetPromoComments(context.Context, *GetPromoCommentsRequest) (*GetPromoCommentsResponse, error)
	TrackClientRegistration(context.Context, *TrackClientRegistrationRequest) (*TrackClientRegistrationResponse, error)
	TrackPromoCreated(context.Context, *TrackPromoCreatedRequest) (*TrackPromoCreatedResponse, error)
	TrackPromoUpdated(context.Context, *TrackPromoUpdatedRequest) (*TrackPromoUpdatedResponse, error)
	TrackPromoDeleted(context.Context, *TrackPromoDeletedRequest) (*TrackPromoDeletedResponse, error)
	TrackUserProfileUpdate(context.Context, *TrackUserProfileUpdateRequest) (*TrackUserProfileUpdateResponse, error)
	mustEmbedUnimplementedEventServiceServer()
}

// UnimplementedEventServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventServiceServer struct{}

func (UnimplementedEventServiceServer) TrackPromoView(context.Context, *TrackPromoViewRequest) (*TrackPromoViewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TrackPromoView not implemented")
}
func (UnimplementedEventServiceServer) TrackPromoClick(context.Context, *TrackPromoClickRequest) (*TrackPromoClickResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TrackPromoClick not implemented")
}
func (UnimplementedEventServiceServer) TrackPromoComment(context.Context, *TrackPromoCommentRequest) (*TrackPromoCommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TrackPromoComment not implemented")
}
func (UnimplementedEventServiceServer) GetPromoComments(context.Context, *GetPromoCommentsRequest) (*GetPromoCommentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPromoComments not implemented")
}
func (UnimplementedEventServiceServer) TrackClientRegistration(context.Context, *TrackClientRegistrationRequest) (*TrackClientRegistrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TrackClientRegistration not implemented")
}
func (UnimplementedEventServiceServer) TrackPromoCreated(context.Context, *TrackPromoCreatedRequest) (*TrackPromoCreatedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TrackPromoCreated not implemented")
}
func (UnimplementedEventServiceServer) TrackPromoUpdated(context.Context, *TrackPromoUpdatedRequest) (*TrackPromoUpdatedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TrackPromoUpdated not implemented")
}
func (UnimplementedEventServiceServer) TrackPromoDeleted(context.Context, *TrackPromoDeletedRequest) (*TrackPromoDeletedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TrackPromoDeleted not implemented")
}
func (UnimplementedEventServiceServer) TrackUserProfileUpdate(context.Context, *TrackUserProfileUpdateRequest) (*TrackUserProfileUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TrackUserProfileUpdate not implemented")
}
func (UnimplementedEventServiceServer) mustEmbedUnimplementedEventServiceServer() {}
func (UnimplementedEventServiceServer) testEmbeddedByValue()                      {}

// UnsafeEventServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventServiceServer will
// result in compilation errors.
type UnsafeEventServiceServer interface {
	mustEmbedUnimplementedEventServiceServer()
}

func RegisterEventServiceServer(s grpc.ServiceRegistrar, srv EventServiceServer) {
	// If the following call pancis, it indicates UnimplementedEventServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventService_ServiceDesc, srv)
}

func _EventService_TrackPromoView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrackPromoViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).TrackPromoView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_TrackPromoView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).TrackPromoView(ctx, req.(*TrackPromoViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_TrackPromoClick_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrackPromoClickRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).TrackPromoClick(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_TrackPromoClick_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).TrackPromoClick(ctx, req.(*TrackPromoClickRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_TrackPromoComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrackPromoCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).TrackPromoComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_TrackPromoComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).TrackPromoComment(ctx, req.(*TrackPromoCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetPromoComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPromoCommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetPromoComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetPromoComments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetPromoComments(ctx, req.(*GetPromoCommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_TrackClientRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrackClientRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).TrackClientRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_TrackClientRegistration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).TrackClientRegistration(ctx, req.(*TrackClientRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_TrackPromoCreated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrackPromoCreatedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).TrackPromoCreated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_TrackPromoCreated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).TrackPromoCreated(ctx, req.(*TrackPromoCreatedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_TrackPromoUpdated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrackPromoUpdatedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).TrackPromoUpdated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_TrackPromoUpdated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).TrackPromoUpdated(ctx, req.(*TrackPromoUpdatedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_TrackPromoDeleted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrackPromoDeletedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).TrackPromoDeleted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_TrackPromoDeleted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).TrackPromoDeleted(ctx, req.(*TrackPromoDeletedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_TrackUserProfileUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrackUserProfileUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).TrackUserProfileUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_TrackUserProfileUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).TrackUserProfileUpdate(ctx, req.(*TrackUserProfileUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EventService_ServiceDesc is the grpc.ServiceDesc for EventService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "event.EventService",
	HandlerType: (*EventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TrackPromoView",
			Handler:    _EventService_TrackPromoView_Handler,
		},
		{
			MethodName: "TrackPromoClick",
			Handler:    _EventService_TrackPromoClick_Handler,
		},
		{
			MethodName: "TrackPromoComment",
			Handler:    _EventService_TrackPromoComment_Handler,
		},
		{
			MethodName: "GetPromoComments",
			Handler:    _EventService_GetPromoComments_Handler,
		},
		{
			MethodName: "TrackClientRegistration",
			Handler:    _EventService_TrackClientRegistration_Handler,
		},
		{
			MethodName: "TrackPromoCreated",
			Handler:    _EventService_TrackPromoCreated_Handler,
		},
		{
			MethodName: "TrackPromoUpdated",
			Handler:    _EventService_TrackPromoUpdated_Handler,
		},
		{
			MethodName: "TrackPromoDeleted",
			Handler:    _EventService_TrackPromoDeleted_Handler,
		},
		{
			MethodName: "TrackUserProfileUpdate",
			Handler:    _EventService_TrackUserProfileUpdate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "event/event.proto",
}
