// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: promo/promo.proto

package promo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserRole int32

const (
	UserRole_UNKNOWN  UserRole = 0
	UserRole_CUSTOMER UserRole = 1
	UserRole_BUSINESS UserRole = 2
)

// Enum value maps for UserRole.
var (
	UserRole_name = map[int32]string{
		0: "UNKNOWN",
		1: "CUSTOMER",
		2: "BUSINESS",
	}
	UserRole_value = map[string]int32{
		"UNKNOWN":  0,
		"CUSTOMER": 1,
		"BUSINESS": 2,
	}
)

func (x UserRole) Enum() *UserRole {
	p := new(UserRole)
	*p = x
	return p
}

func (x UserRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserRole) Descriptor() protoreflect.EnumDescriptor {
	return file_promo_promo_proto_enumTypes[0].Descriptor()
}

func (UserRole) Type() protoreflect.EnumType {
	return &file_promo_promo_proto_enumTypes[0]
}

func (x UserRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserRole.Descriptor instead.
func (UserRole) EnumDescriptor() ([]byte, []int) {
	return file_promo_promo_proto_rawDescGZIP(), []int{0}
}

type Promo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CreatorId      string                 `protobuf:"bytes,4,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	DiscountAmount float64                `protobuf:"fixed64,5,opt,name=discount_amount,json=discountAmount,proto3" json:"discount_amount,omitempty"`
	Code           string                 `protobuf:"bytes,6,opt,name=code,proto3" json:"code,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	IsActive       bool                   `protobuf:"varint,9,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	ValidUntil     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=valid_until,json=validUntil,proto3" json:"valid_until,omitempty"`
	MaxUses        int32                  `protobuf:"varint,11,opt,name=max_uses,json=maxUses,proto3" json:"max_uses,omitempty"`
	CurrentUses    int32                  `protobuf:"varint,12,opt,name=current_uses,json=currentUses,proto3" json:"current_uses,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Promo) Reset() {
	*x = Promo{}
	mi := &file_promo_promo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Promo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Promo) ProtoMessage() {}

func (x *Promo) ProtoReflect() protoreflect.Message {
	mi := &file_promo_promo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Promo.ProtoReflect.Descriptor instead.
func (*Promo) Descriptor() ([]byte, []int) {
	return file_promo_promo_proto_rawDescGZIP(), []int{0}
}

func (x *Promo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Promo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Promo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Promo) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *Promo) GetDiscountAmount() float64 {
	if x != nil {
		return x.DiscountAmount
	}
	return 0
}

func (x *Promo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Promo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Promo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Promo) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Promo) GetValidUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidUntil
	}
	return nil
}

func (x *Promo) GetMaxUses() int32 {
	if x != nil {
		return x.MaxUses
	}
	return 0
}

func (x *Promo) GetCurrentUses() int32 {
	if x != nil {
		return x.CurrentUses
	}
	return 0
}

type CreatePromoRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	DiscountAmount float64                `protobuf:"fixed64,3,opt,name=discount_amount,json=discountAmount,proto3" json:"discount_amount,omitempty"`
	Code           string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	ValidUntil     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=valid_until,json=validUntil,proto3" json:"valid_until,omitempty"`
	MaxUses        int32                  `protobuf:"varint,6,opt,name=max_uses,json=maxUses,proto3" json:"max_uses,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreatePromoRequest) Reset() {
	*x = CreatePromoRequest{}
	mi := &file_promo_promo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePromoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePromoRequest) ProtoMessage() {}

func (x *CreatePromoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_promo_promo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePromoRequest.ProtoReflect.Descriptor instead.
func (*CreatePromoRequest) Descriptor() ([]byte, []int) {
	return file_promo_promo_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePromoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePromoRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreatePromoRequest) GetDiscountAmount() float64 {
	if x != nil {
		return x.DiscountAmount
	}
	return 0
}

func (x *CreatePromoRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreatePromoRequest) GetValidUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidUntil
	}
	return nil
}

func (x *CreatePromoRequest) GetMaxUses() int32 {
	if x != nil {
		return x.MaxUses
	}
	return 0
}

type CreatePromoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Promo         *Promo                 `protobuf:"bytes,1,opt,name=promo,proto3" json:"promo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePromoResponse) Reset() {
	*x = CreatePromoResponse{}
	mi := &file_promo_promo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePromoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePromoResponse) ProtoMessage() {}

func (x *CreatePromoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_promo_promo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePromoResponse.ProtoReflect.Descriptor instead.
func (*CreatePromoResponse) Descriptor() ([]byte, []int) {
	return file_promo_promo_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePromoResponse) GetPromo() *Promo {
	if x != nil {
		return x.Promo
	}
	return nil
}

type DeletePromoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePromoRequest) Reset() {
	*x = DeletePromoRequest{}
	mi := &file_promo_promo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePromoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePromoRequest) ProtoMessage() {}

func (x *DeletePromoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_promo_promo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePromoRequest.ProtoReflect.Descriptor instead.
func (*DeletePromoRequest) Descriptor() ([]byte, []int) {
	return file_promo_promo_proto_rawDescGZIP(), []int{3}
}

func (x *DeletePromoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeletePromoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePromoResponse) Reset() {
	*x = DeletePromoResponse{}
	mi := &file_promo_promo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePromoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePromoResponse) ProtoMessage() {}

func (x *DeletePromoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_promo_promo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePromoResponse.ProtoReflect.Descriptor instead.
func (*DeletePromoResponse) Descriptor() ([]byte, []int) {
	return file_promo_promo_proto_rawDescGZIP(), []int{4}
}

type UpdatePromoRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	DiscountAmount float64                `protobuf:"fixed64,4,opt,name=discount_amount,json=discountAmount,proto3" json:"discount_amount,omitempty"`
	Code           string                 `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	ValidUntil     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=valid_until,json=validUntil,proto3" json:"valid_until,omitempty"`
	MaxUses        int32                  `protobuf:"varint,7,opt,name=max_uses,json=maxUses,proto3" json:"max_uses,omitempty"`
	IsActive       bool                   `protobuf:"varint,8,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdatePromoRequest) Reset() {
	*x = UpdatePromoRequest{}
	mi := &file_promo_promo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePromoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePromoRequest) ProtoMessage() {}

func (x *UpdatePromoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_promo_promo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePromoRequest.ProtoReflect.Descriptor instead.
func (*UpdatePromoRequest) Descriptor() ([]byte, []int) {
	return file_promo_promo_proto_rawDescGZIP(), []int{5}
}

func (x *UpdatePromoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePromoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePromoRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdatePromoRequest) GetDiscountAmount() float64 {
	if x != nil {
		return x.DiscountAmount
	}
	return 0
}

func (x *UpdatePromoRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UpdatePromoRequest) GetValidUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidUntil
	}
	return nil
}

func (x *UpdatePromoRequest) GetMaxUses() int32 {
	if x != nil {
		return x.MaxUses
	}
	return 0
}

func (x *UpdatePromoRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type UpdatePromoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Promo         *Promo                 `protobuf:"bytes,1,opt,name=promo,proto3" json:"promo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePromoResponse) Reset() {
	*x = UpdatePromoResponse{}
	mi := &file_promo_promo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePromoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePromoResponse) ProtoMessage() {}

func (x *UpdatePromoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_promo_promo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePromoResponse.ProtoReflect.Descriptor instead.
func (*UpdatePromoResponse) Descriptor() ([]byte, []int) {
	return file_promo_promo_proto_rawDescGZIP(), []int{6}
}

func (x *UpdatePromoResponse) GetPromo() *Promo {
	if x != nil {
		return x.Promo
	}
	return nil
}

type GetPromoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPromoRequest) Reset() {
	*x = GetPromoRequest{}
	mi := &file_promo_promo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPromoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPromoRequest) ProtoMessage() {}

func (x *GetPromoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_promo_promo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPromoRequest.ProtoReflect.Descriptor instead.
func (*GetPromoRequest) Descriptor() ([]byte, []int) {
	return file_promo_promo_proto_rawDescGZIP(), []int{7}
}

func (x *GetPromoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetPromoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Promo         *Promo                 `protobuf:"bytes,1,opt,name=promo,proto3" json:"promo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPromoResponse) Reset() {
	*x = GetPromoResponse{}
	mi := &file_promo_promo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPromoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPromoResponse) ProtoMessage() {}

func (x *GetPromoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_promo_promo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPromoResponse.ProtoReflect.Descriptor instead.
func (*GetPromoResponse) Descriptor() ([]byte, []int) {
	return file_promo_promo_proto_rawDescGZIP(), []int{8}
}

func (x *GetPromoResponse) GetPromo() *Promo {
	if x != nil {
		return x.Promo
	}
	return nil
}

type ListPromosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	CreatorId     string                 `protobuf:"bytes,3,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	OnlyActive    bool                   `protobuf:"varint,4,opt,name=only_active,json=onlyActive,proto3" json:"only_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPromosRequest) Reset() {
	*x = ListPromosRequest{}
	mi := &file_promo_promo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPromosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPromosRequest) ProtoMessage() {}

func (x *ListPromosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_promo_promo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPromosRequest.ProtoReflect.Descriptor instead.
func (*ListPromosRequest) Descriptor() ([]byte, []int) {
	return file_promo_promo_proto_rawDescGZIP(), []int{9}
}

func (x *ListPromosRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPromosRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListPromosRequest) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *ListPromosRequest) GetOnlyActive() bool {
	if x != nil {
		return x.OnlyActive
	}
	return false
}

type ListPromosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Promos        []*Promo               `protobuf:"bytes,1,rep,name=promos,proto3" json:"promos,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPromosResponse) Reset() {
	*x = ListPromosResponse{}
	mi := &file_promo_promo_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPromosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPromosResponse) ProtoMessage() {}

func (x *ListPromosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_promo_promo_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPromosResponse.ProtoReflect.Descriptor instead.
func (*ListPromosResponse) Descriptor() ([]byte, []int) {
	return file_promo_promo_proto_rawDescGZIP(), []int{10}
}

func (x *ListPromosResponse) GetPromos() []*Promo {
	if x != nil {
		return x.Promos
	}
	return nil
}

func (x *ListPromosResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListPromosResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPromosResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

var File_promo_promo_proto protoreflect.FileDescriptor

const file_promo_promo_proto_rawDesc = "" +
	"\n" +
	"\x11promo/promo.proto\x12\x05promo\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb7\x03\n" +
	"\x05Promo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x04 \x01(\tR\tcreatorId\x12'\n" +
	"\x0fdiscount_amount\x18\x05 \x01(\x01R\x0ediscountAmount\x12\x12\n" +
	"\x04code\x18\x06 \x01(\tR\x04code\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1b\n" +
	"\tis_active\x18\t \x01(\bR\bisActive\x12;\n" +
	"\vvalid_until\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"validUntil\x12\x19\n" +
	"\bmax_uses\x18\v \x01(\x05R\amaxUses\x12!\n" +
	"\fcurrent_uses\x18\f \x01(\x05R\vcurrentUses\"\xdf\x01\n" +
	"\x12CreatePromoRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12'\n" +
	"\x0fdiscount_amount\x18\x03 \x01(\x01R\x0ediscountAmount\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\x12;\n" +
	"\vvalid_until\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"validUntil\x12\x19\n" +
	"\bmax_uses\x18\x06 \x01(\x05R\amaxUses\"9\n" +
	"\x13CreatePromoResponse\x12\"\n" +
	"\x05promo\x18\x01 \x01(\v2\f.promo.PromoR\x05promo\"$\n" +
	"\x12DeletePromoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x15\n" +
	"\x13DeletePromoResponse\"\x8c\x02\n" +
	"\x12UpdatePromoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12'\n" +
	"\x0fdiscount_amount\x18\x04 \x01(\x01R\x0ediscountAmount\x12\x12\n" +
	"\x04code\x18\x05 \x01(\tR\x04code\x12;\n" +
	"\vvalid_until\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"validUntil\x12\x19\n" +
	"\bmax_uses\x18\a \x01(\x05R\amaxUses\x12\x1b\n" +
	"\tis_active\x18\b \x01(\bR\bisActive\"9\n" +
	"\x13UpdatePromoResponse\x12\"\n" +
	"\x05promo\x18\x01 \x01(\v2\f.promo.PromoR\x05promo\"!\n" +
	"\x0fGetPromoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"6\n" +
	"\x10GetPromoResponse\x12\"\n" +
	"\x05promo\x18\x01 \x01(\v2\f.promo.PromoR\x05promo\"\x84\x01\n" +
	"\x11ListPromosRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x03 \x01(\tR\tcreatorId\x12\x1f\n" +
	"\vonly_active\x18\x04 \x01(\bR\n" +
	"onlyActive\"\x81\x01\n" +
	"\x12ListPromosResponse\x12$\n" +
	"\x06promos\x18\x01 \x03(\v2\f.promo.PromoR\x06promos\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize*3\n" +
	"\bUserRole\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\f\n" +
	"\bCUSTOMER\x10\x01\x12\f\n" +
	"\bBUSINESS\x10\x022\xe0\x02\n" +
	"\fPromoService\x12D\n" +
	"\vCreatePromo\x12\x19.promo.CreatePromoRequest\x1a\x1a.promo.CreatePromoResponse\x12D\n" +
	"\vDeletePromo\x12\x19.promo.DeletePromoRequest\x1a\x1a.promo.DeletePromoResponse\x12D\n" +
	"\vUpdatePromo\x12\x19.promo.UpdatePromoRequest\x1a\x1a.promo.UpdatePromoResponse\x12;\n" +
	"\bGetPromo\x12\x16.promo.GetPromoRequest\x1a\x17.promo.GetPromoResponse\x12A\n" +
	"\n" +
	"ListPromos\x12\x18.promo.ListPromosRequest\x1a\x19.promo.ListPromosResponseB\x1aZ\x18promoservice/proto/promob\x06proto3"

var (
	file_promo_promo_proto_rawDescOnce sync.Once
	file_promo_promo_proto_rawDescData []byte
)

func file_promo_promo_proto_rawDescGZIP() []byte {
	file_promo_promo_proto_rawDescOnce.Do(func() {
		file_promo_promo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_promo_promo_proto_rawDesc), len(file_promo_promo_proto_rawDesc)))
	})
	return file_promo_promo_proto_rawDescData
}

var file_promo_promo_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_promo_promo_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_promo_promo_proto_goTypes = []any{
	(UserRole)(0),                 // 0: promo.UserRole
	(*Promo)(nil),                 // 1: promo.Promo
	(*CreatePromoRequest)(nil),    // 2: promo.CreatePromoRequest
	(*CreatePromoResponse)(nil),   // 3: promo.CreatePromoResponse
	(*DeletePromoRequest)(nil),    // 4: promo.DeletePromoRequest
	(*DeletePromoResponse)(nil),   // 5: promo.DeletePromoResponse
	(*UpdatePromoRequest)(nil),    // 6: promo.UpdatePromoRequest
	(*UpdatePromoResponse)(nil),   // 7: promo.UpdatePromoResponse
	(*GetPromoRequest)(nil),       // 8: promo.GetPromoRequest
	(*GetPromoResponse)(nil),      // 9: promo.GetPromoResponse
	(*ListPromosRequest)(nil),     // 10: promo.ListPromosRequest
	(*ListPromosResponse)(nil),    // 11: promo.ListPromosResponse
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_promo_promo_proto_depIdxs = []int32{
	12, // 0: promo.Promo.created_at:type_name -> google.protobuf.Timestamp
	12, // 1: promo.Promo.updated_at:type_name -> google.protobuf.Timestamp
	12, // 2: promo.Promo.valid_until:type_name -> google.protobuf.Timestamp
	12, // 3: promo.CreatePromoRequest.valid_until:type_name -> google.protobuf.Timestamp
	1,  // 4: promo.CreatePromoResponse.promo:type_name -> promo.Promo
	12, // 5: promo.UpdatePromoRequest.valid_until:type_name -> google.protobuf.Timestamp
	1,  // 6: promo.UpdatePromoResponse.promo:type_name -> promo.Promo
	1,  // 7: promo.GetPromoResponse.promo:type_name -> promo.Promo
	1,  // 8: promo.ListPromosResponse.promos:type_name -> promo.Promo
	2,  // 9: promo.PromoService.CreatePromo:input_type -> promo.CreatePromoRequest
	4,  // 10: promo.PromoService.DeletePromo:input_type -> promo.DeletePromoRequest
	6,  // 11: promo.PromoService.UpdatePromo:input_type -> promo.UpdatePromoRequest
	8,  // 12: promo.PromoService.GetPromo:input_type -> promo.GetPromoRequest
	10, // 13: promo.PromoService.ListPromos:input_type -> promo.ListPromosRequest
	3,  // 14: promo.PromoService.CreatePromo:output_type -> promo.CreatePromoResponse
	5,  // 15: promo.PromoService.DeletePromo:output_type -> promo.DeletePromoResponse
	7,  // 16: promo.PromoService.UpdatePromo:output_type -> promo.UpdatePromoResponse
	9,  // 17: promo.PromoService.GetPromo:output_type -> promo.GetPromoResponse
	11, // 18: promo.PromoService.ListPromos:output_type -> promo.ListPromosResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_promo_promo_proto_init() }
func file_promo_promo_proto_init() {
	if File_promo_promo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_promo_promo_proto_rawDesc), len(file_promo_promo_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_promo_promo_proto_goTypes,
		DependencyIndexes: file_promo_promo_proto_depIdxs,
		EnumInfos:         file_promo_promo_proto_enumTypes,
		MessageInfos:      file_promo_promo_proto_msgTypes,
	}.Build()
	File_promo_promo_proto = out.File
	file_promo_promo_proto_goTypes = nil
	file_promo_promo_proto_depIdxs = nil
}
